# Generated by Django 2.1.7 on 2019-04-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_number', models.IntegerField()),
                ('time_stamp', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=50)),
            ],
        ),
    ]
