# Generated by Django 2.1.7 on 2019-04-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20190404_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=1)),
                ('time_stamp', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=50)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=50)),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=1)),
                ('imo', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ships',
            },
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AddField(
            model_name='positions',
            name='imo_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Ships'),
        ),
    ]
