# Generated by Django 2.1.7 on 2019-04-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190404_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=50),
        ),
        migrations.AlterField(
            model_name='positions',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=50),
        ),
    ]
